### ISSUE TITLE
[GigEV] how to pull MotionCam data at 1120x800

### ISSUE THREAD

**Issue by bmegli** [photoneo-3d/photoneo-cpp-examples#1]
I am trying to pull data over GigE Vision, also with `ConnectAndGrab`.

I can get data at 560x800.

I have trouble getting data at 1120x800.

## Settings

```bash
rv-tool-0.8 control CameraResolution
Photoneo-MotionCam-3D Color-TRD-058 (192.168.0.194)
CameraResolution = Resolution_1120x800```
```

```bash
arv-tool-0.8 control AcquisitionMode
Photoneo-MotionCam-3D Color-TRD-058 (192.168.0.194)
AcquisitionMode = Continuous
```

```bash
arv-tool-0.8 control OperationMode
Photoneo-MotionCam-3D Color-TRD-058 (192.168.0.194)
OperationMode = Camera
```

## Sample Output

```bash
./ConnectAndGrab 192.168.0.194
Connected to camera: MotionCam-3D Color
Width: 560px
Height: 800px
Reprojection matrix size: 3584000
Payload size: 2688016 bytes
Acquisition started...
IMAGE buffer:
Width: 560
Height: 800
CHUNK DATA buffer:
DepthMap received
-------------------------------
# output trimmed (same/similar)
```

## Question

How to make the camera output 1120x800 over GigEV?

**Comment by bmegli** [comment]
Also, it is not possible to set `Width` as it is read-only, e.g.

```bash
arv-tool-0.8 control Width=1120
Photoneo-MotionCam-3D Color-TRD-058 (192.168.0.194)
Width write error: [Width] [Width_Val] GigEVision write_memory error (write-protect)

```

**Comment by illesD** [comment]
**MotionCam-3D** is a bit specific in this field. You cannot change the resolution directly, hence the read-only features.
In order to achieve the desired 1120x800 resolution, you need to change the **OutputTopology** feature.

Take a quick look at our **UserManual** [http://photoneo.com/kb/pxc](http://photoneo.com/kb/pxc)
`Scanning Guide/Scanning Parameters/Capturing parameters (MotionCam-3D)/Camera Mode (MotionCam-3D)`

![image](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/14611079/3eee03a7-9688-4f5d-8488-079a9e4ad221)

```
arv-tool-0.8 control OutputTopology=RegularGrid Width Height
Photoneo-MotionCam-3D Color-###-### (192.168.1.58)
OutputTopology = RegularGrid
Width = 1120 min:0 max:4294967295
Height = 800 min:0 max:4294967295
```

**Comment by bmegli** [comment]
Thank you @illesD,

That did the trick.

It would be helpful to have this information somewhere in GenIcam xml or GigEV readme as it is camera "quirk" like custom pixel format for Texture/RGB.
