### ISSUE TITLE
[GigEV] possibility to disable `CameraTextureSource` completely

### ISSUE THREAD

**Issue by bmegli** [photoneo-3d/photoneo-cpp-examples#8]
Related to:
- #2

## Overview

While making tests of achievable FPS I noticed that
- `CameraTextureSource` affects FPS
-  even if `Intensity` component is disabled

## Specifics

- only `Range` component enabled
- `CameraTextureSource=Color`

Around 10 fps achievable (~10.257)

-  only `Range` component enabled
- `CameraTextureSource=Laser`

Around 14.5 fps achievable (~14.663)

## Questions

1. Is this intended
2. Is there a way to disable `CameraTextureSource` completely? (to get more fps from the camera)
  - not by GenICam features
3. In absence of 2, is `Laser` the fastest "texture source" available if not interested in texture data?

---------------------

Side notes: I am pulling `Range` + `ColorCamera` (raw RGB, not aligned) data. Disabling device side texture computations would further increase FPS from my side

**Comment by yoyko** [comment]
Hi!

`CameraTextureSource=Laser` is indeed the fastest option and it's overhead over a hypothetical "no texture" option should be insignificant, as it is an integral part of our depth calculations.

`Led` adds another exposure in the acquisition phase for the led frame (the exposure time is the same as for the "main" exposure.)

`Color` adds exposure with the color camera (with it's own exposure settings) and also additional computation burden. The exposure happens when `CameraTextureSource` is `Color` or when `ColorCameraImage` is requested. The additional computation time can differ: there is some common processing, but when `CameraTextureSource!=Color`  the re-projection of the color image into the texture doesn't need to happen.

 Thus if `CameraTextureSource==Led` and `ColorCameraImage` is enabled, you get the longest acquisition / lowest fps.

**Comment by bmegli** [comment]
Thank you @yoyko, 

This answers my question fully and explains behavior for all settings.
